# create user first
from django.contrib.auth.models import User

print User.objects.all()
User.objects.create_user('panda', 'panda@gatech.edu', 'panda')
User.objects.create_user('chickenfila', 'chickenfila@gatech.edu', 'chickenfila')
User.objects.create_user('yumbii', 'yumbii@gatech.edu', 'yumbii')
User.objects.create_user('northavenue', 'northavenue@gatech.edu', 'northavenue')
User.objects.create_user('essentialeats', 'essentialeats@gatech.edu', 'essentialeats')
User.objects.create_user('starbucks', 'starbucks@gatech.edu', 'starbucks')

# create serveral rows in the table
from vendor.models import *

resid1 = ResID(name='panda', logo='logo/Pandalogo.png', menu='menu/pandamenu.jpeg')
resid1.save()
hours1 = Hours()
hours1.save()
dish11 = Dish(name='Orange Chicken', resid=resid1)
dish11.save()
dish12 = Dish(name='Mushroom Chicken', resid=resid1)
dish12.save()
dish13 = Dish(name='Grilled Teriyaki', resid=resid1)
dish13.save()
loc1 = Location(address='Student center first floor', latitude="33.773551", longitude="-84.398158")
loc1.save()
usermap1 = UserMap(username='panda', resid=resid1, hours=hours1, loc=loc1)
usermap1.save()

resid2 = ResID(name='Chickenfila', logo='logo/chickenfilalogo.jpeg', menu='menu/chickenfilamenu.jpg')
resid2.save()
hours2 = Hours()
hours2.save()
dish21 = Dish(name='Chicken Sandwich', resid=resid2)
dish21.save()
dish22 = Dish(name='Spicy Sandwich', resid=resid2)
dish22.save()
dish23 = Dish(name='Chicken Nuggets', resid=resid2)
dish23.save()
loc2 = Location(address='Student center first floor', latitude="33.773475", longitude="-84.398184")
loc2.save()
usermap2 = UserMap(username='chickenfila', resid=resid2, hours=hours2, loc=loc2)
usermap2.save()

# food truck
resid3 = ResID(name='yumbii', logo='logo/yumbiilogo.jpeg', menu='menu/yumbiimenu.jpg')
resid3.save()
hours3 = Hours(leftTime='02:20')
hours3.save()
dish31 = Dish(name='Taco', resid=resid3)
dish31.save()
dish32 = Dish(name='Burrito', resid=resid3)
dish32.save()
loc3 = Location(address='West of Clough',  latitude="33.776944", longitude="-84.397680")
loc3.save()
usermap3 = UserMap(username='yumbii', resid=resid3, hours=hours3, loc=loc3)
usermap3.save()

#dining hall
resid4 = ResID(name='northavenue', logo='logo/northavenuelogo.jpeg', menu='menu/northavenuemenu.png')
resid4.save()
hours4 = Hours()
hours4.save()
dish41 = Dish(name='Hamburger', resid=resid4)
dish41.save()
dish42 = Dish(name='YellowRice', resid=resid4)
dish42.save()
loc4 = Location(address='East Campus at 120 N Ave NW', latitude="33.771095", longitude="-84.391585")
loc4.save()
usermap4 = UserMap(username='northavenue', resid=resid4, hours=hours4, loc=loc4)
usermap4.save()

#food court
resid5 = ResID(name='essentialeats', logo='logo/essentialeatslogo.jpeg', menu='menu/essentialeatsmenu.png')
resid5.save()
hours5 = Hours()
hours5.save()
dish51 = Dish(name='Blackend chicken slider', resid=resid5)
dish51.save()
dish52 = Dish(name='Red beans & rice', resid=resid5)
dish52.save()
loc5 = Location(address='Student center second floor', latitude="33.773885", longitude="-84.398705")
loc5.save()
usermap5 = UserMap(username='essentialeats', resid=resid5, hours=hours5, loc=loc5)
usermap5.save()

#inside building
resid6 = ResID(name='starbucks', logo='logo/starbuckslogo.png', menu='menu/starbucksmenu.jpg')
resid6.save()
hours6 = Hours()
hours6.save()
dish61 = Dish(name='Cappuccino', resid=resid6)
dish61.save()
dish62 = Dish(name='Mocha', resid=resid6)
dish62.save()
loc6 = Location(address='First floor of Clough', latitude="33.774249", longitude="-84.396243")
loc6.save()
usermap6 = UserMap(username='starbucks', resid=resid6, hours=hours6, loc=loc6)
usermap6.save()


